<a href="https://colab.research.google.com/github/marianatmatos/estudos/blob/main/Broadcasting_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The goal of this notebook is to understand and show examples of broadcasting with NumPy.

<p align="center">
  <img  height="200" src="https://i.pinimg.com/564x/5d/74/ab/5d74aba409999dc83476b4c0e596119f.jpg" >
</p>

Broadcasting is the way NumPy treats arrays with different shapes for arithmetic operations. Basically, the smaller array is broadcasted across the larger array so that they have compatible shapes, how it shows in the figure above.

We have the matrix (4,3) and we want to sum with the matrix (3,), the way NumPy deals with it is vectorizing array operations without making needless copies of data thus leads to efficient implementations. 



In [8]:
# Import necessary lib
import numpy as np

Let's see some cases

In [15]:
# Case 1: Multiplying arrays with the same shape
a = np.array([1,2,3,4])
b = np.array([2,2,2,2])
a * b

array([2, 4, 6, 8])

In [16]:
# Case 2: Broadcasting
a = np.array([1,2,3,4])
b = 2
a * b

array([2, 4, 6, 8])

We see that for both cases the output is the same but the second case uses broadcasting. Numpy is smart enough to use the original scalar value without creating any copies making broadcasting operations more efficient as possible.

Let's run some exemples

In [26]:
# Example 1: 'a' is m-dimensional array (m,n) and 'b' is one-dimensional array (1,m)
a = np.random.rand(2,3)
b = np.array([[1,2,3]])
c = a + b
print('a + b:\n', c)
print('\nShape of a:', a.shape)
print('Shape of b:', b.shape)
print('Shape of a + b: ', c.shape)

a + b:
 [[1.10096565 2.54791469 3.85210624]
 [1.69339873 2.60418549 3.89751136]]

Shape of a: (2, 3)
Shape of b: (1, 3)
Shape of a + b:  (2, 3)


In [27]:
# Example 2: 'a' is m-dimensional array (m,n) and 'b' is m-dimensional array (m,1)
a = np.random.rand(2,3)x
b = np.array([[1,2,]]).T
c = a + b
print('a + b:\n', c)
print('\nShape of a:', a.shape)
print('Shape of b:', b.shape)
print('Shape of a + b: ', c.shape)

a + b:
 [[1.9606779  1.68883568 1.95719885]
 [2.21456754 2.51867947 2.62428633]]

Shape of a: (2, 3)
Shape of b: (2, 1)
Shape of a + b:  (2, 3)


In [29]:
# Example 3: 'a' is m-dimensional array (m,n) and 'b' is a scalar number
a = np.random.rand(1,4)
b = 2
c = a + b
print('a + b:\n', c)
print('\nShape of a:', a.shape)
print('Shape of a + b: ', c.shape)

a + b:
 [[2.52438315 2.26038949 2.08707457 2.38498733]]

Shape of a: (1, 4)
Shape of a + b:  (1, 4)


In [30]:
# Example 4: 'a' is one-dimensional array (1,n) 'b' is a scalar number
a = np.random.rand(1,4)
b = 2
c = a + b
print('a + b:\n', c)
print('\nShape of a:', a.shape)
print('Shape of a + b: ', c.shape)


a + b:
 [[2.8572755  2.81875771 2.98192826 2.04959665]]

Shape of a: (1, 4)
Shape of a + b:  (1, 4)


**References:**

[broadcasting in python - Andrew NG](https://www.coursera.org/learn/neural-networks-deep-learning/lecture/uBuTv/broadcasting-in-python)

[Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

[broadcasting in python - Pooja Mahajan](https://poojamahajan5131.medium.com/broadcasting-in-python-b98ea517c51d)